"""add drawing_embeddings for pgvector AI search

Revision ID: 3f3366d51f41
Revises: ec884d8cb9bd
Create Date: 2026-07-10 10:16:31.954379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3f3366d51f41'
down_revision: Union[str, Sequence[str], None] = 'ec884d8cb9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Managed Postgres providers usually pre-enable this or grant rights to
    # do so, same situation as CREATE EXTENSION postgis in the baseline
    # migration; self-hosted/local dev needs it explicitly.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('annotation_id', sa.String(length=64), nullable=True),
    sa.Column('label_hint', sa.String(length=100), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=0, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no explicit geom index here — geoalchemy2 manages
    # idx_drawing_embeddings_geom itself via an after_create DDL event fired
    # by op.create_table() above (see the initial-baseline migration for the
    # duplicate-index bug this avoids). idx_drawing_embeddings_vector (HNSW)
    # has no such automatic management, so it IS explicit below.
    op.create_index('idx_drawing_embeddings_vector', 'drawing_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_drawing_embeddings_id'), 'drawing_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawing_embeddings_id'), table_name='drawing_embeddings')
    op.drop_index('idx_drawing_embeddings_vector', table_name='drawing_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('drawing_embeddings')  # geoalchemy2 drops idx_drawing_embeddings_geom itself (before_drop event)
    # ### end Alembic commands ###
