"""add plan-set ingestion fields to drawings

Revision ID: 50f4005e345c
Revises: 3f3366d51f41
Create Date: 2026-07-10 15:27:59.927890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f4005e345c'
down_revision: Union[str, Sequence[str], None] = '3f3366d51f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('page_number', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('drawings', sa.Column('total_pages', sa.Integer(), nullable=True))
    op.add_column('drawings', sa.Column('sheet_number', sa.String(length=50), nullable=True))
    op.add_column('drawings', sa.Column('discipline', sa.String(length=10), nullable=True))
    op.add_column('drawings', sa.Column('upload_batch_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_drawings_upload_batch_id'), 'drawings', ['upload_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawings_upload_batch_id'), table_name='drawings')
    op.drop_column('drawings', 'upload_batch_id')
    op.drop_column('drawings', 'discipline')
    op.drop_column('drawings', 'sheet_number')
    op.drop_column('drawings', 'total_pages')
    op.drop_column('drawings', 'page_number')
    # ### end Alembic commands ###
