"""add share links for external no-account collaboration

Revision ID: 602fbe46c011
Revises: 38fbc1e04b33
Create Date: 2026-07-17 13:32:23.656529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602fbe46c011'
down_revision: Union[str, Sequence[str], None] = '38fbc1e04b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'COMMENT', name='sharelinkpermission'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_id'), 'share_links', ['id'], unique=False)
    op.create_index(op.f('ix_share_links_project_id'), 'share_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.add_column('comments', sa.Column('guest_name', sa.String(length=100), nullable=True))
    op.add_column('comments', sa.Column('share_link_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_comments_share_link_id', 'comments', 'share_links', ['share_link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Named explicitly on both sides -- autogenerate's create_foreign_key(None, ...)
    # leaves Postgres to auto-name the constraint, which then has no name
    # for this drop to reference (same bug hit + fixed in
    # b93c8c83cc5c_add_drawing_folders_and_project_color.py; verified there
    # via CompileError before naming it explicitly).
    op.drop_constraint('fk_comments_share_link_id', 'comments', type_='foreignkey')
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'share_link_id')
    op.drop_column('comments', 'guest_name')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_project_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_id'), table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
    # sa.Enum's CREATE TYPE has no automatic DROP TYPE on table drop (verified:
    # re-running upgrade after downgrade failed with DuplicateObject on this
    # exact type until this was added) -- same pattern as
    # dc9aac8a90e5_add_user_roles_and_org_invites.py's downgrade().
    op.execute('DROP TYPE IF EXISTS sharelinkpermission')
