"""add cost code mappings and handoff audit events

Revision ID: 6e1672d332cb
Revises: 2ccc26455bd6
Create Date: 2026-07-10 16:24:13.049814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1672d332cb'
down_revision: Union[str, Sequence[str], None] = '2ccc26455bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_code_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('wbs_code', sa.String(length=50), nullable=True),
    sa.Column('upc_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('target_system', sa.Enum('PROCORE', 'DESTINI', 'EDIPHI', 'GENERIC', name='handofftargetsystem'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_code_mappings_id'), 'cost_code_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_cost_code_mappings_project_id'), 'cost_code_mappings', ['project_id'], unique=False)
    op.create_index('ux_cost_code_mappings_project_trade_item', 'cost_code_mappings', ['project_id', 'trade', 'item'], unique=True)
    op.create_table('handoff_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('target_system', sa.Enum('PROCORE', 'DESTINI', 'EDIPHI', 'GENERIC', name='handofftargetsystem'), nullable=True),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['cost_code_mappings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_audit_events_id'), 'handoff_audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_handoff_audit_events_project_id'), 'handoff_audit_events', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoff_audit_events_project_id'), table_name='handoff_audit_events')
    op.drop_index(op.f('ix_handoff_audit_events_id'), table_name='handoff_audit_events')
    op.drop_table('handoff_audit_events')
    op.drop_index('ux_cost_code_mappings_project_trade_item', table_name='cost_code_mappings')
    op.drop_index(op.f('ix_cost_code_mappings_project_id'), table_name='cost_code_mappings')
    op.drop_index(op.f('ix_cost_code_mappings_id'), table_name='cost_code_mappings')
    op.drop_table('cost_code_mappings')
    op.execute('DROP TYPE IF EXISTS handofftargetsystem')
    # ### end Alembic commands ###
