"""add master units for repeating groups

Revision ID: b6977e619493
Revises: dc9aac8a90e5
Create Date: 2026-07-11 12:29:15.440698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6977e619493'
down_revision: Union[str, Sequence[str], None] = 'dc9aac8a90e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_units_id'), 'master_units', ['id'], unique=False)
    op.create_index(op.f('ix_master_units_project_id'), 'master_units', ['project_id'], unique=False)
    op.create_index('ux_master_units_drawing_id', 'master_units', ['drawing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_master_units_drawing_id', table_name='master_units')
    op.drop_index(op.f('ix_master_units_project_id'), table_name='master_units')
    op.drop_index(op.f('ix_master_units_id'), table_name='master_units')
    op.drop_table('master_units')
    # ### end Alembic commands ###
