"""add drawing folders and project color

Revision ID: b93c8c83cc5c
Revises: b6977e619493
Create Date: 2026-07-17 11:32:04.934956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93c8c83cc5c'
down_revision: Union[str, Sequence[str], None] = 'b6977e619493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_folders_id'), 'drawing_folders', ['id'], unique=False)
    op.add_column('drawings', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_drawings_folder_id', 'drawings', 'drawing_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'color')
    # Autogenerate emitted create_foreign_key(None, ...) above, which Postgres
    # names automatically at create time -- but that leaves the drop side
    # with no name to reference (verified: CompileError, "it has no name").
    # Named explicitly on both sides so downgrade actually works.
    op.drop_constraint('fk_drawings_folder_id', 'drawings', type_='foreignkey')
    op.drop_column('drawings', 'folder_id')
    op.drop_index(op.f('ix_drawing_folders_id'), table_name='drawing_folders')
    op.drop_table('drawing_folders')
    # ### end Alembic commands ###
