"""add user roles and org invites

Revision ID: dc9aac8a90e5
Revises: a8c2f331acef
Create Date: 2026-07-10 17:03:17.793469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9aac8a90e5'
down_revision: Union[str, Sequence[str], None] = 'a8c2f331acef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitestatus'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_index(op.f('ix_invites_organization_id'), 'invites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    # server_default is required to backfill NOT NULL on a non-empty
    # `users` table; dropped again right after so future inserts rely on
    # the ORM-level default (models.User.role) as the single source of
    # truth, not a DB-level one left lying around.
    op.add_column('users', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False, server_default='MEMBER'))
    # Data fix: every org today has exactly one user by construction (see
    # auth_routes.py's signup — always creates a brand-new org), so that
    # user is retroactively its owner. Written generically (earliest
    # created_at per org, not "the only user") so it's still correct if
    # that 1:1 assumption is ever violated by a future backfill.
    op.execute("""
        UPDATE users SET role = 'OWNER'
        WHERE id IN (
            SELECT DISTINCT ON (organization_id) id
            FROM users
            WHERE organization_id IS NOT NULL
            ORDER BY organization_id, created_at ASC, id ASC
        )
    """)
    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_index(op.f('ix_invites_organization_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.execute('DROP TYPE IF EXISTS invitestatus')
    op.execute('DROP TYPE IF EXISTS userrole')
    # ### end Alembic commands ###
