"""add condition.unit_cost for Area x Unit Cost formula

Revision ID: ec884d8cb9bd
Revises: 704876dee09b
Create Date: 2026-07-10 08:43:35.732306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec884d8cb9bd'
down_revision: Union[str, Sequence[str], None] = '704876dee09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('unit_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'unit_cost')
    # ### end Alembic commands ###
